# Example: How to use the release workflow template in your Java backend project
# Copy this file to .github/workflows/release.yml in your project

name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., 1.0.0)'
        required: true
        default: '1.0.0'
        type: string

jobs:
  release:
    uses: ./.github/workflow-templates/release.yml
    with:
      version: ${{ github.event.inputs.version }}
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 