name: CI Template

on:
  workflow_call:
    secrets:
      GH_PACKAGES_TOKEN:
        description: 'GitHub Packages token for accessing private packages'
        required: false

permissions:
  contents: read
  packages: read

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Application
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: wrapper

      - name: Build with Gradle
        env:
          CI: true
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN || github.token }}
        run: ./gradlew build --no-daemon --stacktrace

  test:
    runs-on: ubuntu-latest
    name: Run Tests
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: wrapper

      - name: Run tests
        env:
          CI: true
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN || github.token }}
        run: ./gradlew test --no-daemon --stacktrace

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: build/test-results/test/ 